-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 19:33:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coworker_freeorder_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coworker_freeorder_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coworker_freeorder_final` DEFAULT CHARACTER SET latin1 ;
USE `coworker_freeorder_final` ;

-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`sectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`sectores` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `sect_image` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'http://co-workers.com.co/adaris/freeorder/img/sectores/',
  `sect_name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sect_description` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`restaurants` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `sect_rest` INT(10) NOT NULL,
  `rest_image` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'http://co-workers.com.co/adaris/freeorder/img/restaurantes/',
  `rest_name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rest_description` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sect_rest` (`sect_rest` ASC),
  CONSTRAINT `sect_rest`
    FOREIGN KEY (`sect_rest`)
    REFERENCES `coworker_freeorder_final`.`sectores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`categorias_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`categorias_menu` (
  `cat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rest_category` INT(10) NOT NULL,
  `cat_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cat_descripcion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cat_image` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'http://co-workers.com.co/adaris/freeorder/img/categorias/',
  `categorias_menu_cat_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cat_id`),
  UNIQUE INDEX `cat_id_UNIQUE` (`cat_id` ASC),
  INDEX `fk_categorias_menu_categorias_menu1_idx` (`categorias_menu_cat_id` ASC),
  INDEX `category_rest` (`rest_category` ASC),
  CONSTRAINT `category_rest`
    FOREIGN KEY (`rest_category`)
    REFERENCES `coworker_freeorder_final`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_menu_categorias_menu1`
    FOREIGN KEY (`categorias_menu_cat_id`)
    REFERENCES `coworker_freeorder_final`.`categorias_menu` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`productos` (
  `pro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `pro_descripcion` VARCHAR(250) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `pro_valor` INT(20) NOT NULL,
  `pro_image` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `categorias_menu_cat_id` INT(11) NOT NULL,
  `pro_comentario` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `pro_cantidad` INT(10) NOT NULL DEFAULT '1',
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `pro_id_UNIQUE` (`pro_id` ASC),
  INDEX `fk_productos_categorias_menu_idx` (`categorias_menu_cat_id` ASC),
  CONSTRAINT `fk_productos_categorias_menu`
    FOREIGN KEY (`categorias_menu_cat_id`)
    REFERENCES `coworker_freeorder_final`.`categorias_menu` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`adicionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`adicionales` (
  `adi_pk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `adicionales_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `adicionales_valor` VARCHAR(45) NULL,
  `productos_pro_id` INT(11) NOT NULL,
  PRIMARY KEY (`adi_pk_id`),
  UNIQUE INDEX `idadicionales_UNIQUE` (`adi_pk_id` ASC),
  INDEX `fk_adicionales_productos1_idx` (`productos_pro_id` ASC),
  CONSTRAINT `fk_adicionales_productos1`
    FOREIGN KEY (`productos_pro_id`)
    REFERENCES `coworker_freeorder_final`.`productos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`mesas` (
  `mes_pk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mes_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `restaurants_id` INT(10) NOT NULL,
  PRIMARY KEY (`mes_pk_id`),
  UNIQUE INDEX `mes_pk_id_UNIQUE` (`mes_pk_id` ASC),
  INDEX `fk_mesas_restaurants1_idx` (`restaurants_id` ASC),
  CONSTRAINT `fk_mesas_restaurants1`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `coworker_freeorder_final`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`pagos` (
  `pag_pk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `valorCuenta` INT(11) NOT NULL,
  `formaPago` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `pag_fecha` TIMESTAMP NULL DEFAULT NULL,
  `pedidos_ped_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`pag_pk_id`),
  UNIQUE INDEX `pag_pk_id_UNIQUE` (`pag_pk_id` ASC),
  INDEX `fk_pagos_pedidos1_idx` (`pedidos_ped_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`users` (
  `use_id` INT(11) NOT NULL AUTO_INCREMENT,
  `use_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `use_apellidos` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `use_correo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `use_contrasena` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `use_fecha_nacimiento` DATE NULL DEFAULT NULL,
  `use_genero` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `use_telefono` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `use_direccion` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `use_codPostal` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `use_ciudad` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`use_id`),
  UNIQUE INDEX `use_id_UNIQUE` (`use_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`pedidos` (
  `ped_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ped_fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_use_id` INT(11) NOT NULL,
  `mesas_mes_pk_id` INT(11) NOT NULL,
  PRIMARY KEY (`ped_id`),
  INDEX `fk_pedidos_users1_idx` (`users_use_id` ASC),
  INDEX `fk_pedidos_mesas1_idx` (`mesas_mes_pk_id` ASC),
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`mesas_mes_pk_id`)
    REFERENCES `coworker_freeorder_final`.`mesas` (`mes_pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_users1`
    FOREIGN KEY (`users_use_id`)
    REFERENCES `coworker_freeorder_final`.`users` (`use_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`tamaños`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`tamaños` (
  `tam_pk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tam_nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `productos_pro_id` INT(11) NOT NULL,
  PRIMARY KEY (`tam_pk_id`),
  UNIQUE INDEX `tam_pk_id_UNIQUE` (`tam_pk_id` ASC),
  INDEX `fk_tamaños_productos1_idx` (`productos_pro_id` ASC),
  CONSTRAINT `fk_tamaños_productos1`
    FOREIGN KEY (`productos_pro_id`)
    REFERENCES `coworker_freeorder_final`.`productos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`pedidos_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`pedidos_has_productos` (
  `ped_pk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pedidos_ped_id` INT(10) UNSIGNED NOT NULL,
  `productos_pro_id` INT(11) NOT NULL,
  `ped_comentario` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `tamanos_tam_pk_id` INT(11) NOT NULL,
  PRIMARY KEY (`ped_pk_id`),
  UNIQUE INDEX `ped_pk_id_UNIQUE` (`ped_pk_id` ASC),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`productos_pro_id` ASC),
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`pedidos_ped_id` ASC),
  INDEX `fk_pedidos_has_productos_tamaños1_idx` (`tamanos_tam_pk_id` ASC),
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`pedidos_ped_id`)
    REFERENCES `coworker_freeorder_final`.`pedidos` (`ped_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`productos_pro_id`)
    REFERENCES `coworker_freeorder_final`.`productos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_tamaños1`
    FOREIGN KEY (`tamanos_tam_pk_id`)
    REFERENCES `coworker_freeorder_final`.`tamaños` (`tam_pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`solicitar_mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`solicitar_mesero` (
  `sol_mes_pk_id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `mesas_mes_pk_id` INT(11) NOT NULL,
  PRIMARY KEY (`sol_mes_pk_id`),
  UNIQUE INDEX `sol_mes_pk_id_UNIQUE` (`sol_mes_pk_id` ASC),
  INDEX `solicitar_mesero` (`id_user` ASC),
  INDEX `fk_solicitar_mesero_mesas1_idx` (`mesas_mes_pk_id` ASC),
  CONSTRAINT `fk_solicitar_mesero_mesas1`
    FOREIGN KEY (`mesas_mes_pk_id`)
    REFERENCES `coworker_freeorder_final`.`mesas` (`mes_pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitar_mesero`
    FOREIGN KEY (`id_user`)
    REFERENCES `coworker_freeorder_final`.`users` (`use_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coworker_freeorder_final`.`pedidos_has_productos_has_adicionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coworker_freeorder_final`.`pedidos_has_productos_has_adicionales` (
  `pedidos_has_productos_ped_pk_id` INT(11) NOT NULL,
  `adicionales_adi_pk_id` INT(11) NOT NULL,
  PRIMARY KEY (`pedidos_has_productos_ped_pk_id`, `adicionales_adi_pk_id`),
  INDEX `fk_pedidos_has_productos_has_adicionales_adicionales1_idx` (`adicionales_adi_pk_id` ASC),
  INDEX `fk_pedidos_has_productos_has_adicionales_pedidos_has_produc_idx` (`pedidos_has_productos_ped_pk_id` ASC),
  CONSTRAINT `fk_pedidos_has_productos_has_adicionales_pedidos_has_productos1`
    FOREIGN KEY (`pedidos_has_productos_ped_pk_id`)
    REFERENCES `coworker_freeorder_final`.`pedidos_has_productos` (`ped_pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_has_adicionales_adicionales1`
    FOREIGN KEY (`adicionales_adi_pk_id`)
    REFERENCES `coworker_freeorder_final`.`adicionales` (`adi_pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
